version: "3.9"

services:
    app:
        image: localbrandx
        container_name: localbrandx
        build:
            context: .
            dockerfile: Dockerfile
        ports: [ "9000:80" ]
        networks: [ localbrandx ]

    redis:
        image: redis
        container_name: redis
        ports: [ "6379:6379" ]
        volumes:
            - redis:/data
        networks: [ localbrandx ]

    mysql:
        image: mysql
        container_name: mysql
        ports: [ "3309:3306" ]
        volumes:
            - mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: localbrandx
            MYSQL_ROOT_PASSWORD: password
        networks: [ localbrandx ]

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports: [ "5000:80" ]
        environment:
            PMA_HOST: mysql
        networks: [ localbrandx ]

networks:
    localbrandx:
        name: localbrandx
        driver: bridge

volumes:
    mysql:
        name: mysql
        driver: local
    redis:
        name: redis
        driver: local
